#pragma once
#include <open62541/client_config_default.h>
#include <open62541/client_highlevel.h>
#include <open62541/client_highlevel_async.h>
#include <open62541/plugin/log_stdout.h>
#include <jde/TypeDefs.h>
#include <jde/Log.h>
#include <jde/App.h>
#include <jde/Str.h>
#include "../../Framework/source/DateTime.h"
#include "../../Framework/source/coroutine/Alarm.h"
#include "../../Framework/source/db/GraphQL.h"
#include "../../Framework/source/db/Database.h"
#include "../../Framework/source/io/AsioContextThread.h"
#include "../../Framework/source/io/Socket.h"
#include "../../Public/src/web/RestServer.h"
#include "types/proto/IotFromServer.pb.h"
#include "types/proto/IotFromClient.pb.h"
#include "types/FromServer.h"
